### ISSUE TITLE
Angular 7 support

### ISSUE THREAD

**Issue by markyleong** [electroma/tslint-forbidden-imports#5]
Upgrading from Angular 6 to 7 produces this error:

```
ng update @angular/core
Package "tslint-forbidden-imports" has an incompatible peer dependency to "typescript" (requires "^2.8.3", would install "3.1.6").
Incompatible peer dependencies found. See above.
```

**Comment by electroma** [comment]
Hey @markyleong!
Thank you for reaching out.
I've upgraded to TypeScript 3.2.2. It should solve the issue. Try version 1.0.7+.
Please let me know if helped in your case.

**Comment by markyleong** [comment]
Thanks for looking into this. Sorry for the delay; was away for the past week. I've tried v1.0.8 but I still get an error:

```
ng update @angular/core
Package "tslint-forbidden-imports" has an incompatible peer dependency to "typescript" (requires "^3.2.2", would install "3.1.6").
Incompatible peer dependencies found. See above.
```

Looks like Angular 7 needs typescript 3.1.6 specifically - https://github.com/angular/angular/blob/master/yarn.lock#L122

```
"@schematics/angular@^7.0.4":
  version "7.0.5"
  resolved "https://registry.yarnpkg.com/@schematics/angular/-/angular-7.0.5.tgz#96a2fc65113e707548ff732583297e40ab96350d"
  integrity sha512-a8oWALnxs4+QwapeeBZfVBq1YEs5bdgmErBecCHioonhHidoBZX0GjJWQOH/TN8qA8HenNDf7b07WN7sRAVC1Q==
  dependencies:
    "@angular-devkit/core" "7.0.5"
    "@angular-devkit/schematics" "7.0.5"
    typescript "3.1.6"
```

**Comment by electroma** [comment]
🤦‍♂️ 
@markyleong 1.0.9 should fix it.
Tested on Angular 7.1.0 project

**Comment by markyleong** [comment]
Confirmed working with Angular 7 now. Thanks! 😄
